package examples;
// This code is auto generated by JTemple, edit at your own risk

public class Index {
    public static String generate(String title, String name) {

        StringBuilder sb = new StringBuilder();
        sb.append("""
        
        <!doctype html>
        <html>
        	<head>
        		<title>""");
        sb.append(title);
        sb.append("""
        </title>
        	</head>
        	<body>
            <h1> Hello """);
        sb.append(name);
        sb.append("""
         </h1>
        	</body>
        </html>
        """);
        return sb.toString().trim();
    }
}
