package examples;
// This code is auto generated by JTemple, edit at your own risk

public class index {
    public static String generate() {

        StringBuilder sb = new StringBuilder();
        sb.append("""package examples;
        // This code is auto generated by JTemple, edit at your own risk
        
        public class index {
            public static String generate() {
        
                StringBuilder sb = new StringBuilder();
                sb.append(\"\"\"package examples;
                // This code is auto generated by JTemple, edit at your own risk
                
                public class index {
                    public static String generate() {
                
                        StringBuilder sb = new StringBuilder();
                        sb.append(\\"\\"\\"package examples;
                        // This code is auto generated by JTemple, edit at your own risk
                        
                        public class index {
                            public static String generate() {
                        
                                StringBuilder sb = new StringBuilder();
                                sb.append(\\\"\\\"\\\"
                                <!DOCTYPE html/>
                                <html>
                                  <head>
                                    <title>Facelet Title</title>
                                  </head>
                                  <body>
                                		\\\"\\\"\\\");
                            
                            			
                            		
                                sb.append(\\\"\\\"\\\"
                                  </body>
                                </html>
                                \\\"\\\"\\\");
                                return sb.toString();
                            }
                        }
                        \\"\\"\\");
                        return sb.toString();
                    }
                }
                \"\"\");
                return sb.toString();
            }
        }
        """);
        return sb.toString();
    }
}
